import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {LogoIcon} from "./components/icons/LogoIcon";
import Sidebar from "./features/sidebar/Sidebar";
import { ModalContext } from "@/lib/context/modalContext";
import { ModalProvider } from "./components/ModalProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=''>
        <ModalProvider>
          <LogoIcon />
          <Sidebar />
          <br></br>
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
