import './globals.css';
import { LogoIcon } from './components/icons/LogoIcon';
import Sidebar from './Sidebar';
import { Metadata } from 'next';
import { ReactNode } from 'react';
import Link from 'next/link';
import { getBoards } from '@/lib/server-actions/board-actions';
import BoardList from '@/app/features/board/components/BoardList';
import AddBoard from '@/app/features/board/components/AddBoard';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const boards = await getBoards();
  return (
    <html className="h-full" lang="en">
      <body className="h-full">
        <div className="grid max-h-screen min-h-full grid-cols-[300px_1fr] grid-rows-[max-content_1fr] gap-x-[2px]">
          <div className="header col-start-1 col-end-2 row-start-1 row-end-2 bg-white">
            <Link href="/">
              {<LogoIcon className="p-8" textColor="fill-black" />}
            </Link>
          </div>
          <div className="col-start-1 col-end-2 row-start-2 row-end-3 h-full">
            <Sidebar>
              <BoardList boards={boards} />
              <AddBoard />
            </Sidebar>
          </div>
          <div className="col-start-2 col-end-3 row-start-1 row-end-3">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
